footprint: [[-0.4, -0.3], [-0.4, 0.3], [0.4, 0.3], [0.4,-0.3]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 4.5
raytrace_range: 5.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: false

obstacles_laser:
    observation_sources: laser
    laser: {sensor_frame: velodyne, data_type: LaserScan, clearing: true, marking: true, topic: scan}
