footprint: [[-0.4, -0.3], [-0.4, 0.3], [0.4, 0.3], [0.4,-0.3]]
footprint_padding: 0.01

robot_base_frame: base_link

resolution: 0.05

obstacle_range: 3.0
raytrace_range: 3.5

#layer definitions
static:
  map_topic: /map
#   subscribe_to_updates: false

inflation:
  cost_scaling_factor: 2.58
  inflation_radius: 1.0

obstacles_laser:
  observation_sources: laser
  laser: {sensor_frame: velodyne, topic: scan, data_type: LaserScan, clearing: true, marking: true}
