# shutdown_costmaps: false

# controller_frequency: 15.0
# controller_patience: 10.0

# planner_frequency: 20.0
# planner_patience: 5.0

# oscillation_timeout: 5.0
# oscillation_distance: 0.5

# recovery_behavior_enabled: true
# clearing_rotation_allowed: true

# conservative_reset_dist: 5.0
# aggressive_reset_dist: 5.0

# max_planning_retries: 3

# max_planning_retries: 10



shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2